---
- name: Deploy NeuralDB Enterprise
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Static configuration based on provided input
    license_path: "/Users/pratikqpranav/Downloads/ndb_enterprise_license.json"
    jwt_secret: "1234"
    admin_mail: "admin@mail.com"
    admin_username: "admin"
    admin_password: "password"
    genai_key: "open-ai-api-key"
    ndb_enterprise_version: "latest"
    autoscaling_enabled: false
    autoscaler_max_count: 1

    shared_file_system_public_ip: "54.176.129.2"
    shared_file_system_private_ip: "192.168.0.127"
    shared_dir: "/opt/neuraldb_enterprise/model_bazaar"
    web_ingress:
      private_ip: "192.168.0.127"
      public_ip: "54.176.129.2"
      run_jobs: true
      ssh_username: "ubuntu"
    create_nfs_server: true
    nfs_clients:
      - private_ip: "192.168.0.74"
    node_ssh_username: "ubuntu"


    nomad_server_public_ip: "54.176.129.2"
    nomad_server_private_ip: "192.168.0.127"
    # Hardcoded facts for SQL server
    self_hosted_sql_server: true
    sql_server_public_ip: "54.176.129.2"
    sql_server_private_ip: "192.168.0.127"
    sql_server_database_dir: "/opt/neuraldb_enterprise/database"
    sql_server_database_password: "password"
    sql_client_private_ips:
      - "192.168.0.74"
    sql_uri: "postgresql://modelbazaaruser:password@192.168.0.127:5432/modelbazaar"

  roles:
    # - common
    # - nfs
    # - license
    # - nomad
    # - postgresql
    # - certs
    - jobs
